In [28]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import tensorflow as tf

In [29]:
with open('label_encoder.pkl', 'rb') as f:
    label_encoder = pickle.load(f)

In [30]:
with open('onehot_encoder.pkl', 'rb') as f:
    onehot_encoder = pickle.load(f)

In [31]:
with open('standard_scaler.pkl', 'rb') as f:
    standard_scaler = pickle.load(f)

In [32]:
loaded_model = load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [33]:
user = {'Pclass': 3, 'Sex': 'female', 'Age': 25, 'SibSp': 1, 'Parch': 1, 'Fare': 7.25, 'Embarked': 'S'}

In [34]:
user_df = pd.DataFrame([user])

In [35]:
user_df

   Pclass     Sex  Age  SibSp  Parch  Fare Embarked
0       3  female   25      1      1  7.25        S

In [36]:
user_df['Sex'] = label_encoder.transform(user_df[['Sex']])

c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [37]:
user_df

   Pclass  Sex  Age  SibSp  Parch  Fare Embarked
0       3    0   25      1      1  7.25        S

In [38]:
embarked_encoded = onehot_encoder.transform(user_df[['Embarked']])

In [39]:
pd.DataFrame(embarked_encoded, columns=onehot_encoder.get_feature_names_out(['Embarked']))

   Embarked_Cherbourg  Embarked_Queenstown  Embarked_Southampton
0                 0.0                  0.0                   0.0

In [40]:
user = pd.concat([user_df.drop('Embarked', axis=1), pd.DataFrame(embarked_encoded, columns=onehot_encoder.get_feature_names_out(['Embarked']))], axis=1)

In [41]:
user

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,3,0,25,1,1,7.25,0.0,0.0,0.0

In [46]:
# Check which features the scaler expects
print(standard_scaler.feature_names_in_)

# Pass all expected columns to transform
scaler_features = standard_scaler.feature_names_in_
user[scaler_features] = standard_scaler.transform(user[scaler_features])

['Pclass' 'Sex' 'SibSp' 'Parch' 'Fare']

In [47]:
user

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,0.82409,-1.359303,25,0.442505,0.83405,-0.536804,0.0,0.0,0.0

In [50]:
y = loaded_model.predict(user)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 525ms/step

In [52]:
y =y[0][0]

In [53]:
y

np.float32(1.0)

In [54]:
if y>= 0.5:
    print("The passenger is predicted to survive.")
else:
    print("The passenger is predicted not to survive.")

The passenger is predicted to survive.

In [ ]:
user = {'Pclass': 3, 'Sex': 'female', 'Age': 25, 'SibSp': 1, 'Parch': 1, 'Fare': 7.25, 'Embarked': 'S'}