In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('C:\\Users\\aboyc\\ANN dude\\huge_1M_titanic.csv')

In [5]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C

In [6]:
data.shape

(1000000, 12)

In [7]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,1.000000e+06,1000000.000000,1000000.00000,801400.000000,1000000.000000,1000000.000000,1000000.000000
mean,5.013095e+05,0.381681,2.31125,29.280339,0.511101,0.360037,33.461097
std,2.886753e+05,0.485799,0.83577,12.744978,1.104846,0.767296,47.976641
min,1.310000e+03,0.000000,1.00000,0.000000,0.000000,0.000000,0.000000
25%,2.513098e+05,0.000000,2.00000,21.000000,0.000000,0.000000,8.568924
50%,5.013095e+05,0.000000,3.00000,29.000000,0.000000,0.000000,15.883647
75%,7.513092e+05,1.000000,3.00000,37.000000,1.000000,0.000000,35.561000
max,1.001309e+06,1.000000,3.00000,114.000000,8.000000,6.000000,640.883614

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  object
 4   Sex          1000000 non-null  object
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  object
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   object
 11  Embarked     997760 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 91.6+ MB

In [9]:
data.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age            198600
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin          770195
Embarked         2240
dtype: int64

In [10]:
data = data.drop(columns=['PassengerId', 'Name', 'Age', 'Ticket', 'Cabin'])

In [11]:
data.shape

(1000000, 7)

In [12]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [13]:
data.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [14]:
data['Embarked'].mode()

0    S
Name: Embarked, dtype: object

In [15]:
data['Embarked'].value_counts()

Embarked
S    729468
C    186846
Q     81446
Name: count, dtype: int64

In [16]:
data['Embarked'].replace({'S':'Southampton', 'C':'Cherbourg', 'Q':'Queenstown'}, inplace=True   )

C:\Users\aboyc\AppData\Local\Temp\ipykernel_26048\1008581005.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Embarked'].replace({'S':'Southampton', 'C':'Cherbourg', 'Q':'Queenstown'}, inplace=True   )

In [17]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare     Embarked
0         1       1  female      0      0  76.760165    Cherbourg
1         0       3    male      0      0  10.193097  Southampton
2         0       3    male      0      0  12.029416    Cherbourg
3         0       3    male      0      0  13.429448  Southampton
4         0       3    male      0      0   4.840769    Cherbourg

In [18]:
data['Embarked'].value_counts()

Embarked
Southampton    729468
Cherbourg      186846
Queenstown      81446
Name: count, dtype: int64

In [19]:
data.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [20]:
data.shape

(1000000, 7)

In [21]:
data['Fare'] = data['Fare'].astype(int)

In [22]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch  Fare     Embarked
0         1       1  female      0      0    76    Cherbourg
1         0       3    male      0      0    10  Southampton
2         0       3    male      0      0    12    Cherbourg
3         0       3    male      0      0    13  Southampton
4         0       3    male      0      0     4    Cherbourg

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()

In [25]:
data['Sex'] = le.fit_transform(data['Sex'])

In [26]:
data.head()

   Survived  Pclass  Sex  SibSp  Parch  Fare     Embarked
0         1       1    0      0      0    76    Cherbourg
1         0       3    1      0      0    10  Southampton
2         0       3    1      0      0    12    Cherbourg
3         0       3    1      0      0    13  Southampton
4         0       3    1      0      0     4    Cherbourg

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
onehot = OneHotEncoder(sparse_output = False)

In [29]:
print(data.columns.tolist())

['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare', 'Embarked']

In [30]:
Embarked = onehot.fit_transform(data[['Embarked']])

In [31]:
Embarked = pd.DataFrame(Embarked, columns=onehot.get_feature_names_out())

In [32]:
Embarked

,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton,Embarked_nan
0,1.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0
4,1.0,0.0,0.0,0.0
...,...,...,...,...
999995,0.0,0.0,1.0,0.0
999996,0.0,0.0,1.0,0.0
999997,0.0,0.0,1.0,0.0
999998,0.0,0.0,1.0,0.0
999999,0.0,0.0,1.0,0.0

In [33]:
data = pd.concat([data.drop(columns=['Embarked']), Embarked], axis=1)

In [34]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton,Embarked_nan
0,1,1,0,0,0,76,1.0,0.0,0.0,0.0
1,0,3,1,0,0,10,0.0,0.0,1.0,0.0
2,0,3,1,0,0,12,1.0,0.0,0.0,0.0
3,0,3,1,0,0,13,0.0,0.0,1.0,0.0
4,0,3,1,0,0,4,1.0,0.0,0.0,0.0

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
scale = StandardScaler()

In [37]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare',
       'Embarked_Cherbourg', 'Embarked_Queenstown', 'Embarked_Southampton',
       'Embarked_nan'],
      dtype='object')

In [38]:
num_cols = ['Pclass', 'Sex', 'SibSp', 'Parch', 'Fare']

In [39]:
data[num_cols]= scale.fit_transform(data[num_cols])

In [40]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton,Embarked_nan
0,1,-1.568913,-1.359303,-0.4626,-0.469229,0.896815,1.0,0.0,0.0,0.0
1,0,0.824090,0.735671,-0.4626,-0.469229,-0.479459,0.0,0.0,1.0,0.0
2,0,0.824090,0.735671,-0.4626,-0.469229,-0.437754,1.0,0.0,0.0,0.0
3,0,0.824090,0.735671,-0.4626,-0.469229,-0.416901,0.0,0.0,1.0,0.0
4,0,0.824090,0.735671,-0.4626,-0.469229,-0.604575,1.0,0.0,0.0,0.0

In [41]:
import pickle

In [42]:
with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(le, f)

In [43]:
with open('onehot_encoder.pkl', 'wb') as f:
    pickle.dump(onehot, f)

In [44]:
with open('standard_scaler.pkl', 'wb') as f:
    pickle.dump(scale, f)

In [45]:
## train test split 
from sklearn.model_selection import train_test_split

X = data.drop(columns=['Survived'])
y = data['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [47]:
X_train.shape, X_valid.shape, X_test.shape

((640000, 9), (160000, 9), (200000, 9))

In [48]:
import sys
!{sys.executable} -m pip install tensorflow

Collecting tensorflow
  Using cached tensorflow-2.21.0-cp310-cp310-win_amd64.whl (350.6 MB)
Collecting opt_einsum>=2.3.2
  Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Requirement already satisfied: six>=1.12.0 in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from tensorflow) (1.17.0)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1
  Using cached gast-0.7.0-py3-none-any.whl (22 kB)
Collecting grpcio<2.0,>=1.24.3
  Downloading grpcio-1.83.0-cp310-cp310-win_amd64.whl (5.2 MB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.2.6)
Collecting termcolor>=1.1.0
  Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Collecting keras>=3.12.0
  Using cached keras-3.12.4-py3-none-any.whl (2.1 MB)
Collecting ml_dtypes<1.0.0,>=0.5.1
  Using cached ml_dtypes-0.6.0-cp310-cp310-win_amd64.whl (433 kB)
Requirement already satisfied: setuptools in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (57.4.0)
Collecting google_pasta>=0.1.1
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.34.2)
Collecting astunparse>=1.6.0
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.3.0)
Collecting absl-py>=1.0.0
  Downloading absl_py-2.5.0-py3-none-any.whl (137 kB)
Collecting flatbuffers>=25.9.23
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: packaging in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from tensorflow) (26.2)
Collecting h5py<3.15.0,>=3.11.0
  Downloading h5py-3.14.0-cp310-cp310-win_amd64.whl (2.9 MB)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (7.35.1)
Collecting libclang>=13.0.0
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)
Collecting wheel<1.0,>=0.23.0
  Downloading wheel-0.48.0-py3-none-any.whl (33 kB)
Collecting rich
  Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Collecting optree
  Downloading optree-0.19.1-cp310-cp310-win_amd64.whl (327 kB)
Collecting namex
  Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.5.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Collecting markdown-it-py>=2.2.0
  Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\aboyc\appdata\roaming\python\python310\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: mdurl, markdown-it-py, wheel, rich, optree, namex, ml-dtypes, h5py, absl-py, termcolor, opt-einsum, libclang, keras, grpcio, google-pasta, gast, flatbuffers, astunparse, tensorflow
Successfully installed absl-py-2.5.0 astunparse-1.6.3 flatbuffers-25.12.19 gast-0.7.0 google-pasta-0.2.0 grpcio-1.83.0 h5py-3.14.0 keras-3.12.4 libclang-18.1.1 markdown-it-py-4.2.0 mdurl-0.1.2 ml-dtypes-0.6.0 namex-0.1.0 opt-einsum-3.4.0 optree-0.19.1 rich-15.0.0 tensorflow-2.21.0 termcolor-3.3.0 wheel-0.48.0

WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
  WARNING: The script markdown-it.exe is installed in 'c:\Users\aboyc\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script wheel.exe is installed in 'c:\Users\aboyc\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts saved_model_cli.exe, tf_upgrade_v2.exe, tflite_convert.exe and toco.exe are installed in 'c:\Users\aboyc\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ysql-connector-python (c:\users\aboyc\appdata\local\programs\python\python310\lib\site-packages)
WARNING: You are using pip version 21.2.3; however, version 26.2.1 is available.
You should consider upgrading via the 'c:\Users\aboyc\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [51]:
import tensorflow

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [56]:
model = Sequential([
    Dense(128, input_shape=(X_train.shape[1],), activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [57]:
model.summary

In [60]:
tensorflow.keras.optimizers.Adam(learning_rate = 0.01)
tensorflow.keras.losses.BinaryFocalCrossentropy

keras.src.losses.losses.BinaryFocalCrossentropy

In [61]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [62]:
X_train,X_valid,y_train,y_valid

(          Pclass       Sex     SibSp     Parch      Fare  Embarked_Cherbourg  \
 338664 -0.372411  0.735671 -0.462600 -0.469229 -0.291786                 0.0
 171390  0.824090 -1.359303 -0.462600 -0.469229 -0.687986                 0.0
 66113   0.824090 -1.359303 -0.462600 -0.469229 -0.333491                 0.0
 981567 -1.568913 -1.359303  0.442505 -0.469229  0.813404                 1.0
 677093 -0.372411  0.735671 -0.462600 -0.469229 -0.604575                 0.0
 ...          ...       ...       ...       ...       ...                 ...
 18622   0.824090  0.735671 -0.462600 -0.469229 -0.437754                 0.0
 17191   0.824090  0.735671 -0.462600 -0.469229 -0.562870                 0.0
 227647 -0.372411 -1.359303 -0.462600  0.834050 -0.291786                 0.0
 639540  0.824090  0.735671 -0.462600 -0.469229 -0.687986                 0.0
 237899  0.824090  0.735671 -0.462600 -0.469229 -0.437754                 0.0

         Embarked_Queenstown  Embarked_Southampton  Embarked_nan
 338664                  0.0                   1.0           0.0
 171390                  0.0                   1.0           0.0
 66113                   0.0                   1.0           0.0
 981567                  0.0                   0.0           0.0
 677093                  0.0                   1.0           0.0
 ...                     ...                   ...           ...
 18622                   0.0                   1.0           0.0
 17191                   1.0                   0.0           0.0
 227647                  0.0                   1.0           0.0
 639540                  0.0                   1.0           0.0
 237899                  0.0                   0.0           1.0

 [640000 rows x 9 columns],
           Pclass       Sex   SibSp     Parch      Fare  Embarked_Cherbourg  \
 866857  0.824090  0.735671 -0.4626 -0.469229 -0.521165                 0.0
 825981 -0.372411  0.735671 -0.4626 -0.469229 -0.062407                 0.0
 456670  0.824090  0.735671 -0.4626 -0.469229 -0.458607                 0.0
 350242 -0.372411  0.735671 -0.4626 -0.469229 -0.687986                 0.0
 732615 -1.568913  0.735671 -0.4626  0.834050  1.459836                 1.0
 ...          ...       ...     ...       ...       ...                 ...
 52427  -0.372411  0.735671 -0.4626 -0.469229 -0.083259                 0.0
 388200  0.824090  0.735671 -0.4626 -0.469229 -0.375196                 0.0
 345762  0.824090  0.735671 -0.4626 -0.469229 -0.521165                 0.0
 456667 -1.568913  0.735671 -0.4626 -0.469229  1.063636                 0.0
 750369 -1.568913  0.735671 -0.4626 -0.469229  1.230457                 1.0

         Embarked_Queenstown  Embarked_Southampton  Embarked_nan
 866857                  0.0                   1.0           0.0
 825981                  0.0                   1.0           0.0
 456670                  0.0                   1.0           0.0
 350242                  0.0                   1.0           0.0
 732615                  0.0                   0.0           0.0
 ...                     ...                   ...           ...
 52427                   0.0                   1.0           0.0
 388200                  0.0                   1.0           0.0
 345762                  1.0                   0.0           0.0
 456667                  0.0                   1.0           0.0
 750369                  0.0                   0.0           0.0

 [160000 rows x 9 columns],
 338664    0
 171390    0
 66113     0
 981567    1
 677093    0
          ..
 18622     0
 17191     0
 227647    1
 639540    0
 237899    0
 Name: Survived, Length: 640000, dtype: int64,
 866857    1
 825981    0
 456670    0
 350242    0
 732615    0
          ..
 52427     0
 388200    0
 345762    0
 456667    0
 750369    1
 Name: Survived, Length: 160000, dtype: int64)

In [63]:
model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=10, batch_size=32, callbacks=[EarlyStopping(patience=5)])

Epoch 1/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 49s 2ms/step - accuracy: 0.8562 - loss: 0.3301 - val_accuracy: 0.8625 - val_loss: 0.3149
Epoch 2/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 44s 2ms/step - accuracy: 0.8649 - loss: 0.3103 - val_accuracy: 0.8670 - val_loss: 0.3077
Epoch 3/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 44s 2ms/step - accuracy: 0.8660 - loss: 0.3072 - val_accuracy: 0.8678 - val_loss: 0.3037
Epoch 4/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 44s 2ms/step - accuracy: 0.8665 - loss: 0.3054 - val_accuracy: 0.8687 - val_loss: 0.3027
Epoch 5/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 44s 2ms/step - accuracy: 0.8668 - loss: 0.3047 - val_accuracy: 0.8692 - val_loss: 0.3016
Epoch 6/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 44s 2ms/step - accuracy: 0.8671 - loss: 0.3041 - val_accuracy: 0.8687 - val_loss: 0.3024
Epoch 7/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 53s 3ms/step - accuracy: 0.8673 - loss: 0.3036 - val_accuracy: 0.8689 - val_loss: 0.3015
Epoch 8/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 57s 3ms/step - accuracy: 0.8674 - loss: 0.3032 - val_accuracy: 0.8692 - val_loss: 0.3033
Epoch 9/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 57s 3ms/step - accuracy: 0.8674 - loss: 0.3027 - val_accuracy: 0.8682 - val_loss: 0.3023
Epoch 10/10
20000/20000 ━━━━━━━━━━━━━━━━━━━━ 58s 3ms/step - accuracy: 0.8677 - loss: 0.3027 - val_accuracy: 0.8688 - val_loss: 0.3020

In [65]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.