In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("atharvasoundankar/ai-developer-productivity-dataset")

print("Path to dataset files:", path)

c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\aboyc\.cache\kagglehub\datasets\atharvasoundankar\ai-developer-productivity-dataset\versions\1

   hours_coding  coffee_intake_mg  distractions  sleep_hours  commits  \
0          5.99               600             1          5.8        2
1          4.72               568             2          6.9        5
2          6.30               560             1          8.9        2
3          8.05               600             7          6.3        9
4          4.53               421             6          6.9        4

   bugs_reported  ai_usage_hours  cognitive_load  task_success
0              1            0.71             5.4             1
1              3            1.75             4.7             1
2              0            2.27             2.2             1
3              5            1.40             5.9             0
4              0            1.26             6.3             1
(500, 9)

In [7]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hours_coding      500 non-null    float64
 1   coffee_intake_mg  500 non-null    int64
 2   distractions      500 non-null    int64
 3   sleep_hours       500 non-null    float64
 4   commits           500 non-null    int64
 5   bugs_reported     500 non-null    int64
 6   ai_usage_hours    500 non-null    float64
 7   cognitive_load    500 non-null    float64
 8   task_success      500 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB
None

In [8]:
print(data.describe())

       hours_coding  coffee_intake_mg  distractions  sleep_hours    commits  \
count    500.000000        500.000000    500.000000   500.000000  500.00000
mean       5.015600        463.192000      2.976000     6.975800    4.60800
std        1.947253        142.334991      1.678409     1.455965    2.70499
min        0.000000          6.000000      0.000000     3.000000    0.00000
25%        3.600000        369.500000      2.000000     6.100000    3.00000
50%        5.030000        500.500000      3.000000     6.950000    5.00000
75%        6.275000        600.000000      4.000000     7.900000    6.00000
max       12.000000        600.000000      8.000000    10.000000   13.00000

       bugs_reported  ai_usage_hours  cognitive_load  task_success
count     500.000000      500.000000      500.000000    500.000000
mean        0.858000        1.510920        4.498200      0.606000
std         1.102846        1.085557        1.868861      0.489124
min         0.000000        0.000000        1.000000      0.000000
25%         0.000000        0.697500        3.175000      0.000000
50%         0.000000        1.260000        4.400000      1.000000
75%         2.000000        2.070000        5.800000      1.000000
max         5.000000        6.360000       10.000000      1.000000

In [9]:
print(data.isnull().sum())

hours_coding        0
coffee_intake_mg    0
distractions        0
sleep_hours         0
commits             0
bugs_reported       0
ai_usage_hours      0
cognitive_load      0
task_success        0
dtype: int64

In [10]:
print(data.columns.tolist())

['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours', 'commits', 'bugs_reported', 'ai_usage_hours', 'cognitive_load', 'task_success']

In [11]:
data.head()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,5.99,600,1,5.8,2,1,0.71,5.4,1
1,4.72,568,2,6.9,5,3,1.75,4.7,1
2,6.30,560,1,8.9,2,0,2.27,2.2,1
3,8.05,600,7,6.3,9,5,1.40,5.9,0
4,4.53,421,6,6.9,4,0,1.26,6.3,1

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [13]:
X = data.drop(columns=['cognitive_load']) 
y = data['cognitive_load'] # Replace 'target_column' with the actual target column name

In [14]:
X

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,task_success
0,5.99,600,1,5.8,2,1,0.71,1
1,4.72,568,2,6.9,5,3,1.75,1
2,6.30,560,1,8.9,2,0,2.27,1
3,8.05,600,7,6.3,9,5,1.40,0
4,4.53,421,6,6.9,4,0,1.26,1
...,...,...,...,...,...,...,...,...
495,6.08,594,1,5.3,3,0,0.91,1
496,2.93,382,2,6.7,3,2,1.38,0
497,4.62,494,4,7.5,2,0,0.41,1
498,3.25,296,6,6.9,1,0,1.52,0
499,2.23,252,4,8.8,0,0,1.05,0

In [15]:
y

0      5.4
1      4.7
2      2.2
3      5.9
4      6.3
      ...
495    6.8
496    5.9
497    4.5
498    6.3
499    2.6
Name: cognitive_load, Length: 500, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split    
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((400, 8), (100, 8), (400,), (100,))

In [18]:
X_train[['hours_coding','coffee_intake_mg','sleep_hours','commits','bugs_reported','ai_usage_hours']] = scaler.fit_transform(X_train[['hours_coding','coffee_intake_mg','sleep_hours','commits','bugs_reported','ai_usage_hours']])

In [24]:
(X_train.shape[1])

8

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [26]:
model = Sequential([Dense(64,input_shape=(X_train.shape[1],)),Dense(32, activation='linear'),Dense(1, activation='linear')])

c:\Users\aboyc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [28]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [30]:
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2, callbacks=[EarlyStopping(monitor='val_loss', patience=10)])

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - loss: 15.4067 - mean_absolute_error: 3.2623 - val_loss: 7.5463 - val_mean_absolute_error: 2.2295
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 5.6538 - mean_absolute_error: 1.9033 - val_loss: 4.9566 - val_mean_absolute_error: 1.8611
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 4.9440 - mean_absolute_error: 1.7425 - val_loss: 4.0011 - val_mean_absolute_error: 1.6542
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3.6991 - mean_absolute_error: 1.5201 - val_loss: 3.4004 - val_mean_absolute_error: 1.4981
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3.2420 - mean_absolute_error: 1.4288 - val_loss: 2.9737 - val_mean_absolute_error: 1.3834
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2.7805 - mean_absolute_error: 1.3292 - val_loss: 2.4622 - val_mean_absolute_error: 1.2703
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 2.4512 - mean_absolute_error: 1.2474 - val_loss: 2.1562 - val_mean_absolute_error: 1.1739
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 2.1849 - mean_absolute_error: 1.1824 - val_loss: 1.9041 - val_mean_absolute_error: 1.0864
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.9907 - mean_absolute_error: 1.1316 - val_loss: 1.7500 - val_mean_absolute_error: 1.0173
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.8166 - mean_absolute_error: 1.0902 - val_loss: 1.5825 - val_mean_absolute_error: 0.9796
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.6929 - mean_absolute_error: 1.0511 - val_loss: 1.4599 - val_mean_absolute_error: 0.9453
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.5977 - mean_absolute_error: 1.0200 - val_loss: 1.3844 - val_mean_absolute_error: 0.9252
Epoch 13/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.5240 - mean_absolute_error: 0.9953 - val_loss: 1.3226 - val_mean_absolute_error: 0.9126
Epoch 14/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.4778 - mean_absolute_error: 0.9793 - val_loss: 1.3115 - val_mean_absolute_error: 0.9224
Epoch 15/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.4399 - mean_absolute_error: 0.9674 - val_loss: 1.2365 - val_mean_absolute_error: 0.8868
Epoch 16/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.4182 - mean_absolute_error: 0.9571 - val_loss: 1.2298 - val_mean_absolute_error: 0.9002
Epoch 17/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.3690 - mean_absolute_error: 0.9366 - val_loss: 1.2161 - val_mean_absolute_error: 0.8850
Epoch 18/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.3608 - mean_absolute_error: 0.9331 - val_loss: 1.1867 - val_mean_absolute_error: 0.8897
Epoch 19/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.2979 - mean_absolute_error: 0.9116 - val_loss: 1.1751 - val_mean_absolute_error: 0.8742
Epoch 20/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.2780 - mean_absolute_error: 0.9013 - val_loss: 1.1419 - val_mean_absolute_error: 0.8704
Epoch 21/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.2614 - mean_absolute_error: 0.8971 - val_loss: 1.1681 - val_mean_absolute_error: 0.8846
Epoch 22/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.2364 - mean_absolute_error: 0.8880 - val_loss: 1.1104 - val_mean_absolute_error: 0.8586
Epoch 23/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.2109 - mean_absolute_error: 0.8742 - val_loss: 1.1088 - val_mean_absolute_error: 0.8653
Epoch 24/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.1921 - mean_absolute_error: 0.8676 - val_loss: 1.1079 - val_mean_absolute_error: 0.8621
Epoch 25/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.1707 - mean_absolute_error: 0.8601 - val_loss: 1.1027 - val_mean_absolute_error: 0.8650
Epoch 26/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.1659 - mean_absolute_error: 0.8590 - val_loss: 1.0729 - val_mean_absolute_error: 0.8504
Epoch 27/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.1509 - mean_absolute_error: 0.8465 - val_loss: 1.0613 - val_mean_absolute_error: 0.8487
Epoch 28/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.1267 - mean_absolute_error: 0.8372 - val_loss: 1.0489 - val_mean_absolute_error: 0.8363
Epoch 29/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.1411 - mean_absolute_error: 0.8468 - val_loss: 1.0711 - val_mean_absolute_error: 0.8533
Epoch 30/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.0953 - mean_absolute_error: 0.8233 - val_loss: 1.0363 - val_mean_absolute_error: 0.8362
Epoch 31/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.1043 - mean_absolute_error: 0.8290 - val_loss: 1.0086 - val_mean_absolute_error: 0.8188
Epoch 32/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0888 - mean_absolute_error: 0.8183 - val_loss: 1.0433 - val_mean_absolute_error: 0.8459
Epoch 33/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.0916 - mean_absolute_error: 0.8257 - val_loss: 1.0154 - val_mean_absolute_error: 0.8245
Epoch 34/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.0685 - mean_absolute_error: 0.8097 - val_loss: 1.0076 - val_mean_absolute_error: 0.8276
Epoch 35/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.0647 - mean_absolute_error: 0.8093 - val_loss: 1.0202 - val_mean_absolute_error: 0.8281
Epoch 36/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.0701 - mean_absolute_error: 0.8118 - val_loss: 0.9939 - val_mean_absolute_error: 0.8185
Epoch 37/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0675 - mean_absolute_error: 0.8175 - val_loss: 1.0137 - val_mean_absolute_error: 0.8298
Epoch 38/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0751 - mean_absolute_error: 0.8079 - val_loss: 0.9982 - val_mean_absolute_error: 0.8187
Epoch 39/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0463 - mean_absolute_error: 0.8073 - val_loss: 0.9684 - val_mean_absolute_error: 0.8004
Epoch 40/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0555 - mean_absolute_error: 0.8047 - val_loss: 1.0268 - val_mean_absolute_error: 0.8398
Epoch 41/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0180 - mean_absolute_error: 0.7876 - val_loss: 0.9429 - val_mean_absolute_error: 0.7878
Epoch 42/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.0285 - mean_absolute_error: 0.7933 - val_loss: 0.9700 - val_mean_absolute_error: 0.8013
Epoch 43/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0182 - mean_absolute_error: 0.7897 - val_loss: 0.9697 - val_mean_absolute_error: 0.8053
Epoch 44/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0074 - mean_absolute_error: 0.7859 - val_loss: 0.9575 - val_mean_absolute_error: 0.8034
Epoch 45/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0047 - mean_absolute_error: 0.7863 - val_loss: 0.9533 - val_mean_absolute_error: 0.7965
Epoch 46/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0049 - mean_absolute_error: 0.7859 - val_loss: 0.9816 - val_mean_absolute_error: 0.8180
Epoch 47/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0161 - mean_absolute_error: 0.7910 - val_loss: 0.9276 - val_mean_absolute_error: 0.7751
Epoch 48/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9948 - mean_absolute_error: 0.7817 - val_loss: 0.9947 - val_mean_absolute_error: 0.8264
Epoch 49/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9971 - mean_absolute_error: 0.7825 - val_loss: 0.9549 - val_mean_absolute_error: 0.8031
Epoch 50/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9961 - mean_absolute_error: 0.7849 - val_loss: 0.9456 - val_mean_absolute_error: 0.8041
Epoch 51/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0006 - mean_absolute_error: 0.7852 - val_loss: 0.9330 - val_mean_absolute_error: 0.7916
Epoch 52/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0064 - mean_absolute_error: 0.7811 - val_loss: 0.9915 - val_mean_absolute_error: 0.8167
Epoch 53/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0131 - mean_absolute_error: 0.7934 - val_loss: 0.9333 - val_mean_absolute_error: 0.7943
Epoch 54/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.9981 - mean_absolute_error: 0.7809 - val_loss: 0.9422 - val_mean_absolute_error: 0.7865
Epoch 55/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9986 - mean_absolute_error: 0.7859 - val_loss: 0.9680 - val_mean_absolute_error: 0.8207
Epoch 56/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0146 - mean_absolute_error: 0.7933 - val_loss: 0.9375 - val_mean_absolute_error: 0.8011
Epoch 57/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0114 - mean_absolute_error: 0.7904 - val_loss: 0.9429 - val_mean_absolute_error: 0.7935

In [31]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [32]:
y_pred = model.predict(X_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

In [33]:
mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred)

(1899.7355395080624, 42.59911731529236)